FROM node:18-alpine AS deps
WORKDIR /app
# Installing python and build tools for native node modules
RUN apk add --no-cache libc6-compat python3 make g++
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:18-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
ARG APP_NAME
ENV APP_NAME=${APP_NAME}
# Build the specified application
RUN npx nx build ${APP_NAME}

FROM node:18-alpine AS runner
WORKDIR /app
ARG APP_NAME
ENV NODE_ENV=production
ENV APP_NAME=${APP_NAME}
ENV PORT=3000

# Copy the entire workspace to ensure node_modules and dist are present
COPY --from=builder /app ./

EXPOSE 3000

# Run the built app
CMD sh -c "cd dist/apps/${APP_NAME} && npm install --production --legacy-peer-deps && npx next start -p 3000"
